# Generated by Django 3.2.5 on 2021-07-17 09:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirname', models.CharField(max_length=100, null=True)),
                ('filename', models.FileField(null=True, upload_to=app.models.upload_file)),
            ],
        ),
    ]
